apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-tutorialsonline
    app.kubernetes.io/part-of: angular-app-test
  name: angular-15-client-tutorialsonline
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: angular-15-client-tutorialsonline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: angular-15-client-tutorialsonline
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/atul-fulambarkar-tenant/angular-app-test/angular-15-client-tutorialsonline@sha256:5ae16bcc9e0b2ea6cdd3b358875c7a96f6caa90b6a51ad3f1662a99bafb1ac98
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
